version: "3.5"

networks:
  todo-network:

services:
  mysql:
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - todo-network
    tty: true
    environment:
      MYSQL_DATABASE: todo-app
      MYSQL_USER: todo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    build:
      context: ./mysql

  phpmyadmin:
    depends_on:
      - mysql
    build:
      context: ./backend/env/phpmyadmin
    tty: true
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - todo-network

  nginx:
    depends_on:
      - phpmyadmin
      - react
      - php-fpm
      - php-cli
    build:
      context: ./nginx
    tty: true
    ports:
      - "8000:80"
      - "8001:81"
      - "8002:82"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend/app/todolist:/var/app/backend
      - ./frontend:/var/app/frontend/www
      - ./mysql:/var/app/mysql
    networks:
      - todo-network

  php-cli:
    build:
      context: ./backend/env/php-cli
    tty: true
    volumes:
      - ./backend/app/todolist:/var/app/backend
    networks:
      - todo-network

  php-fpm:
    depends_on:
      - mysql
    env_file:
      - ./backend/env/php-fpm/.env
    build:
      context: ./backend/env/php-fpm
      args:
        APP_ENV: ${APP_ENV}
    tty: true
    working_dir: /var/app/backend
    volumes:
      - ./backend/app/todolist:/var/app/backend
    networks:
      - todo-network

  composer:
    depends_on:
      - php-fpm
    build:
      context: ./backend/env/composer
    volumes:
      - ./backend/app/todolist:/var/app/backend
    tty: true
    stdin_open: true

  react:
    build:
      context: frontend
    tty: true
    environment:
      PORT: 80
    expose:
      - "9000:80"
      - "9229:9229"
    volumes:
      - ./frontend:/var/app/frontend/www
    networks:
      - todo-network
