version: '3'

networks:
  todo-network:

services:
  mysql:
    build:
      context: ./mysql
    volumes:
    - ./mysql:/var/app/mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo-app
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
    networks:
      - todo-network

  phpmyadmin:
    depends_on:
      - mysql
    build:
      context: ./backend/env/phpmyadmin
    tty: true
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - todo-network

  nginx:
    depends_on:
      - phpmyadmin
      - react
      - php-fpm
      - php-cli
    build:
      context: ./nginx
    tty: true
    ports:
      - "8000:80"
      - "8001:81"
      - "8002:82"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./backend/app/todolist:/var/app/backend
      - ./frontend:/var/app/frontend/www
      - ./mysql:/var/app/mysql
    networks:
      - todo-network

  php-cli:
    build:
      context: ./backend/env/php-cli
    tty: true
    volumes:
      - ./backend/app/todolist:/var/app/backend
    networks:
      - todo-network

  php-fpm:
    depends_on:
      - mysql
    build:
      context: ./backend/env/php-fpm
    tty: true
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - ./backend/app/todolist:/var/app/backend
    networks:
      - todo-network

  composer:
    depends_on:
      - php-fpm
    build:
      context: ./backend/env/composer
    volumes:
      - ./backend/app/todolist:/var/app/backend
    tty: true
    stdin_open: true

  react:
    build:
      context: frontend
    tty: true
    environment:
      PORT: 80
    volumes:
    - ./frontend:/var/app/frontend/www
    networks:
      - todo-network
